apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  OPENAI_ASSISTANT_ID: {{ .Values.secrets.OPENAI_ASSISTANT_ID | b64enc }}
  OPENAI_KEY: {{ .Values.secrets.OPENAI_KEY | b64enc }}
