apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: uamgl/gpt-widget-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ASPNETCORE_URLS
            - name: OPENAI_ASSISTANT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_ASSISTANT_ID
            - name: OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_KEY
