version: '3.8'

services:
  frontend:
    image: nginx:latest
    container_name: gpt-widget-frontend
    volumes:
      - ../Frontend/:/usr/share/nginx/html
      - ./Frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ../
      dockerfile: ./Docker/ASPNET/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=demo
    env_file:
      - .env
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
