version: '3.8'

services:
  frontend:
    build:
      context: ../
      dockerfile: Docker/Frontend/Dockerfile
    image: gpt-widget/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ../
      dockerfile: ./Docker/ASPNET/Dockerfile
    image: gpt-widget/api:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
